src/Tehtävät/Tehtava1

Initial commit Tehtävä 1

---

src/Tehtävät/Tehtava1.js
src/Tehtävät/Tehtava2.js

File extensions are missing from earlier commit.

Fix for missing file extensions in earlier commit

---

src/App.js
src/Tehtävät/Email/Email.css
src/Tehtävät/Email/Email.js

At least something to show to the customer. Going to ask more about the specs of the exercise from them at the meeting.
Sorry for taking this long!

Email/attachement file exercise // not ready yet, this is just the mvp

---

src/Tehtävät/Email/Email.css
src/Tehtävät/Email/Email.js

Email exercise is now functional within the specs given by the customer
(Basically the whole page and logic was re-written and heavy use of tutorials will be visible in the code, but hey, if it works...)

Email exercise now fully functional

---

src/App.css
src/App.js
src/Home.css
src/Home.js

CSS tyylittelyä yleisilmeelle ja etusivulle

Yleisilme ja etusivu tyylitelty

---

src/App.js
src/Tehtävät/Eform/Eform.css
src/Tehtävät/Eform/Eform.js

E-form working. Doesn't look that finished yet, as there is some problems with the view height in the CSS of the page. Will fix later!

E-form exercise done, only minor CSS details missing

---

src/Tehtävät/Eform/Eform.css
src/Tehtävät/Eform/Eform.js
src/Tehtävät/Email/Email.css
src/Tehtävät/Email/Email.js

E-form and email exercises now fully functional and complete. The next step is to make it look more presentable, but that will be done in co-operation with Sandra at a later date.

E form test branch

---

src/Tehtävät/Email/Email.js

Email exercise validation now complete

State handling rewritten and validation added

---

src/Tehtävät/Eform/Eform.js
src/Tehtävät/Eform/Form.js

state handling rewritten and validation added

Eform validation now complete

---

src/Tehtävät/Tietosuoja/Tietosuoja.css
src/Tehtävät/Tietosuoja/Tietosuoja.js

Pull request on behalf of @ikonenjoel because Github is acting weirdly (again).

Test branch frontend

---

src/Tehtävät/Eform/Eform.js
src/Tehtävät/Eform/Form.js
src/Tehtävät/Email/Email.js
src/Tehtävät/Email/common-form.css

CSS is now up to Sandra's design.
I'll create a new pull request for the final validation update later today

Email and eform CSS update

---

src/Tehtävät/Eform/Eform.js
src/Tehtävät/Email/Email.js
src/Tehtävät/Email/common-form.css

CSS fixed, tweaked text according to customers request

Css fixed, some minor tweaks in text

---

src/App.js
src/Tehtävät/Tietoturva/tietoturva.css
src/Tehtävät/Tietoturva/tietoturva.js

DONE
-InfoSec questionnaire logic
-scoring system
-minor adjustment of eform link text in the nav bar
TODO:
-Styling
-removal of the old version

Questionnaire exercise logic and scoring done

---

src/Tehtävät/Tippuvat kirjaimet/FallingGame.css
src/Tehtävät/Tippuvat kirjaimet/FallingGame.js
src/Tehtävät/Tippuvat sanat/FallingWords.js
src/Tehtävät/Vedä&Pudota/VedaJaPudota.js

Reworked difficulty, changed font, and made some minor fixes

Vedajapudota test

---

src/Home.js
src/Tehtävät/Editointi/Tehtava1.js
src/Tehtävät/Kirjoitus/Tehtava2.js

Timer and logic updates for task1 and task2

Task1 task2 update

---

src/App.js
src/Home.js
src/Tehtävät/Editointi/Tehtava1.js
src/Tehtävät/Kirjoitus/Tehtava2.js
src/Tehtävät/Kopiointi/Kopiointi.js

- Updates from earlier customer requests for task1 and task2
- Added tutorial videos for frontpage. Import react-player and actual video and just position the video element where it is actually needed.
- Removed links for tietosuoja

Added stuff

---

src/App.css
src/Tehtävät/Tietoturva/tietoturva.css
src/Tehtävät/Tietoturva/tietoturva.js

Questionnaire CSS ready for review

Questionnaire layout

---

src/Tehtävät/Tietoturva/tietoturva.js

New questions added to the questionnaire

---

src/Tehtävät/Eform/Eform.js
src/Tehtävät/Eform/Form.js
src/Tehtävät/Email/Email.js

text fixes

---

src/Tehtävät/Tietoturva/tietoturva.js

Explanations to correct answers added

---

README.md

Updated readMe file

---

package-lock.json
src/Tehtävät/Tippuvat kirjaimet/FallingGame.js
src/Tehtävät/Tippuvat sanat/FallingWords.js

Fixed losing text disappearing after few seconds in both FallingGames

---

src/App.css
src/App.js

Footer added (includes prettier formatting changes)
